packages:
  - app-vite
  - app-webpack
  - vite-plugin
  - vite-plugin/playground
  - extras
  - ui
  - ui/playground
  - ui/testing
  - create-quasar
  - cli
  - docs
  - utils/render-ssr-error
  - utils/ssl-certificate
  - utils/eslint-config
  - playground/app-vite-ts

# The packages below are not included. Use their individual folders.
# - icongenie
# - utils/babel-preset-app
# - utils/ssr-helpers

catalog:
  eslint: ^9.37.0
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-7ee085e9ae3b2ccda8287c542bf4b23f324b910f
  vitest: npm:@voidzero-dev/vite-plus-test@0.0.0-7ee085e9ae3b2ccda8287c542bf4b23f324b910f
  '@voidzero-dev/vite-plus': 0.0.0-7ee085e9ae3b2ccda8287c542bf4b23f324b910f

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
